
import React, { useState } from 'react';
import { 
  Send, Loader2, Share2, Target, 
  Rocket, Search, ArrowLeft, GitFork, 
  Layers, BookOpen, Clock, Youtube, FileText, Globe,
  CheckCircle2, AlertCircle, ArrowRight, Activity, ChevronDown, ChevronUp, Star, Atom, Trash2, Calendar, X
} from 'lucide-react';
import { generateRoadmap } from '../../services/geminiService';
import { createCourseFromRoadmap } from '../../services/courseService';
import { saveRoadmap, getUserRoadmaps, SavedRoadmap, deleteRoadmap } from '../../services/roadmapService';
import { DetailedRoadmap, RoadmapPhase, RoadmapTopic, Course } from '../../types';
import CourseView from './CourseView';

interface RoadmapGeneratorProps {
  onCourseCreated?: (course: Course) => void;
  userId?: string;
  initialQuery?: string;
}

const RoadmapGenerator: React.FC<RoadmapGeneratorProps> = ({ onCourseCreated, userId = 'mock-user-id', initialQuery }) => {
  const [input, setInput] = useState(initialQuery || '');
  const [experienceLevel, setExperienceLevel] = useState('Beginner');
  const [timeCommitment, setTimeCommitment] = useState('10 hours/week');
  
  const [loading, setLoading] = useState(false);
  const [courseLoading, setCourseLoading] = useState(false);
  const [result, setResult] = useState<DetailedRoadmap | null>(null);
  const [generatedCourse, setGeneratedCourse] = useState<Course | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'input' | 'roadmap' | 'course'>('input');
  const [history, setHistory] = useState<SavedRoadmap[]>([]);
  const [currentRoadmapId, setCurrentRoadmapId] = useState<string | null>(null);
  const [lastQuery, setLastQuery] = useState<string>('');
  const hasAutoGenerated = React.useRef(false);

  React.useEffect(() => {
    getUserRoadmaps(userId).then(setHistory);
  }, [userId]);

  React.useEffect(() => {
    if (initialQuery && !result && !loading && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        setInput(initialQuery);
        triggerGeneration(initialQuery);
    }
  }, [initialQuery]);
  
  const triggerGeneration = async (query: string) => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const roadmap = await generateRoadmap(query);
      if (roadmap) {
        setResult(roadmap);
        setGeneratedCourse(null);
        
        saveRoadmap(roadmap, userId).then(saved => {
           if (saved) {
             setHistory(prev => [saved, ...prev]);
             setCurrentRoadmapId(saved.id);
           }
        });
        
        setViewMode('roadmap');
      } else {
        setError("Failed to generate roadmap. Please try a different query.");
      }
    } catch (err) {
      setError("AI Service unavailable. Check console for API Key status.");
    } finally {
      setLoading(false);
    }
  };
  
  const handleGenerate = () => {
    const query = `Goal: ${input}, Level: ${experienceLevel}, Time: ${timeCommitment}`;
    setLastQuery(query);
    triggerGeneration(query);
  };


  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    try {
       await deleteRoadmap(id);
       setHistory(prev => prev.filter(h => h.id !== id));
    } catch (err) {
       console.error("Failed to delete", err);
    }
  };

  const handleCreateCourse = async () => {
    if (!result) return;
    setCourseLoading(true);
    try {
       // Using passed user ID (or default mock for guest)
       const course = await createCourseFromRoadmap(result.role, userId);
       if (course) {
         setGeneratedCourse(course);
         setViewMode('course');
         if (onCourseCreated) onCourseCreated(course);
       }
    } catch (e) {
       console.error(e);
       setError("Failed to create course. Please try again.");
    } finally {
       setCourseLoading(false);
    }
  };

  const [shareToast, setShareToast] = useState(false);
  const [shareModal, setShareModal] = useState(false);
  const [copied, setCopied] = useState(false);

  const getShareUrl = () => {
    if (!currentRoadmapId) return null;
    return `${window.location.origin}/roadmap/${currentRoadmapId}`;
  };

  const handleShareRoadmap = async (_roadmap: DetailedRoadmap) => {
    setShareModal(true);
    setCopied(false);

    // If not saved yet, try saving now
    if (!currentRoadmapId && result && userId !== 'mock-user-id') {
      const saved = await saveRoadmap(result, userId);
      if (saved) {
        setCurrentRoadmapId(saved.id);
        setHistory(prev => {
          // avoid duplicates
          if (prev.find(h => h.id === saved.id)) return prev;
          return [saved, ...prev];
        });
      }
    }
  };

  const handleCopyLink = () => {
    const url = getShareUrl();
    if (!url) return;
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const toggleTopic = (id: string) => {
    setExpandedTopic(expandedTopic === id ? null : id);
  };

  const getResourceIcon = (type: string) => {
    switch(type) {
      case 'video': return <Youtube size={16} className="text-red-500 hover:-rotate-12 transition-transform" />;
      case 'course': return <BookOpen size={16} className="text-amber-500 hover:scale-110 transition-transform" />;
      case 'documentation': return <FileText size={16} className="text-slate-500 hover:scale-110 transition-transform" />;
      default: return <Globe size={16} className="text-emerald-500 shadow-sm" />;
    }
  };

  const [expandedTopic, setExpandedTopic] = useState<string | null>(null);

  const RoadmapView = ({ roadmap }: { roadmap: DetailedRoadmap }) => (
    <div className="animate-reveal max-w-7xl mx-auto space-y-12 pb-24">
      {/* Dynamic Header */}
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
        <div className="space-y-2">
          <button onClick={() => setViewMode('input')} className="group flex items-center gap-3 text-slate-400 hover:text-blue-500 transition-colors font-bold text-xs uppercase tracking-widest">
            <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> Back
          </button>

          <div className="flex flex-col gap-1.5">
            {/* Goal */}
            <div className="flex items-baseline gap-3">
              <h1 className="text-4xl md:text-5xl font-display font-bold tracking-tighter leading-tight">
                <span className="text-slate-900 dark:text-white">Goal</span>
                <span className="text-slate-400 dark:text-slate-500 mx-2">·</span>
                <span className="text-slate-800 dark:text-white">
                  {lastQuery.match(/Goal:\s*([^,]+)/i)?.[1]?.trim() || roadmap.role}
                </span>
              </h1>
            </div>
            {/* Level */}
            <div className="flex items-center gap-3">
              <span className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] w-10 shrink-0">Level</span>
              <span className="text-lg font-black text-blue-500">
                {lastQuery.match(/Level:\s*([^,]+)/i)?.[1]?.trim() || experienceLevel}
              </span>
            </div>
            {/* Pace */}
            <div className="flex items-center gap-3">
              <span className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] w-10 shrink-0">Pace</span>
              <span className="text-lg font-black text-amber-500">
                {lastQuery.match(/Time:\s*([^,]+)/i)?.[1]?.trim() || timeCommitment}
              </span>
            </div>
          </div>
        </div>
        <div className="flex gap-4">
           <button 
             onClick={() => handleShareRoadmap(roadmap)}
             className="bg-white dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-700 px-6 py-4 rounded-2xl flex items-center gap-3 hover:translate-y-[2px] transition-all text-xs font-black uppercase tracking-widest text-slate-600 dark:text-slate-300 shadow-[0_6px_0_rgba(226,232,240,1)] dark:shadow-[0_6px_0_rgba(30,41,59,1)] active:shadow-none active:translate-y-[6px] hover:border-blue-400 hover:text-blue-600 dark:hover:text-blue-400"
           >
             <Share2 size={18} /> Share Log
           </button>
           <button 
             onClick={handleCreateCourse}
             disabled={courseLoading}
             className="bg-emerald-500 text-white border-2 border-emerald-600 px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-[12px] shadow-[0_6px_0_rgba(16,185,129,1)] hover:shadow-[0_4px_0_rgba(16,185,129,1)] hover:translate-y-[2px] active:shadow-none active:translate-y-[6px] transition-all flex items-center gap-2 disabled:opacity-75 disabled:transform-none disabled:shadow-[0_6px_0_rgba(16,185,129,1)]"
           >
             {courseLoading ? <Loader2 className="animate-spin" size={20} /> : <Rocket size={20} className="group-hover/btn:rotate-12" />}
             Start Quest
           </button>
        </div>
      </header>

      {/* Stats Grid */}
      <div className="grid md:grid-cols-12 gap-6">
        {/* Main Info Card */}
        <div className="md:col-span-8 bg-emerald-500 border-4 border-emerald-600 rounded-[2.5rem] p-10 md:p-14 text-white relative overflow-hidden shadow-[0_8px_0_rgba(16,185,129,1)] hover:-translate-y-1 hover:shadow-[0_12px_0_rgba(16,185,129,1)] transition-all flex flex-col justify-between group min-h-[300px]">
          <div className="absolute top-0 right-0 p-10 opacity-20 pointer-events-none group-hover:scale-110 transition-transform duration-700">
             <Target size={300} strokeWidth={0.5} />
          </div>
          <div className="relative z-10 flex flex-col h-full justify-between gap-8">
             <div>
                <div className="inline-flex items-center gap-2 bg-white/20 border-2 border-white/30 px-5 py-2 rounded-[1rem] text-[12px] font-black uppercase tracking-widest mb-6 backdrop-blur-md shadow-[0_4px_0_rgba(255,255,255,0.2)]">
                   Core Architecture
                </div>
                <h2 className="text-4xl md:text-5xl font-display font-black mb-4 tracking-tight leading-tight drop-shadow-md">{roadmap.title}</h2>
                <p className="text-emerald-100 text-xl font-bold leading-relaxed max-w-2xl">{roadmap.description}</p>
             </div>
             
             <div className="flex flex-wrap gap-4">
                <div className="bg-emerald-600/50 backdrop-blur-md border-2 border-emerald-400 rounded-[1.5rem] p-4 flex items-center gap-4 pr-8 shadow-[0_4px_0_rgba(16,185,129,0.5)]">
                   <div className="w-12 h-12 bg-white rounded-xl text-emerald-600 flex items-center justify-center rotate-3 shadow-sm"><Clock size={24} /></div>
                   <div>
                      <p className="text-[10px] font-black uppercase tracking-widest text-emerald-200">Est. Time</p>
                      <p className="text-2xl font-black">~6 Months</p>
                   </div>
                </div>
                <div className="bg-emerald-600/50 backdrop-blur-md border-2 border-emerald-400 rounded-[1.5rem] p-4 flex items-center gap-4 pr-8 shadow-[0_4px_0_rgba(16,185,129,0.5)]">
                   <div className="w-12 h-12 bg-white rounded-xl text-emerald-600 flex items-center justify-center -rotate-3 shadow-sm"><Layers size={24} /></div>
                   <div>
                      <p className="text-[10px] font-black uppercase tracking-widest text-emerald-200">Map Size</p>
                      <p className="text-2xl font-black">{roadmap.phases.length} Levels</p>
                   </div>
                </div>
             </div>
          </div>
        </div>

        {/* Progress Card */}
        <div className="md:col-span-4 bg-white dark:bg-slate-900 border-x-4 border-t-2 border-b-[8px] border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-10 flex flex-col items-center justify-center text-center shadow-none hover:-translate-y-2 transition-all">
           <div className="w-24 h-24 bg-emerald-100 text-emerald-500 rounded-[1.5rem] flex items-center justify-center mb-6 shadow-[0_6px_0_rgba(167,243,208,1)] rotate-3">
              <Activity size={40} className="animate-pulse" />
           </div>
           <p className="text-[12px] font-black text-slate-400 uppercase tracking-[0.3em] mb-2">Campaign Progress</p>
           <h3 className="text-5xl font-display font-black text-slate-800 dark:text-white drop-shadow-sm">0%</h3>
           <p className="mt-4 text-base font-bold text-slate-500">Start your journey today.</p>
        </div>
      </div>

      {/* Timeline Layout */}
      <div className="relative pt-10">
         <div className="absolute left-[29px] md:left-1/2 top-0 bottom-0 w-px bg-slate-200 dark:bg-slate-800 md:-ml-0.5"></div>

         <div className="space-y-16">
            {roadmap.phases.map((phase, idx) => (
              <div key={idx} className={`relative flex flex-col md:flex-row gap-8 items-start ${idx % 2 === 0 ? 'md:flex-row-reverse' : ''}`}>
                 
                 {/* Center Node */}
                 <div className="absolute left-[13px] md:left-1/2 top-8 w-8 h-8 bg-white dark:bg-slate-900 border-4 border-amber-500 rounded-full z-10 md:-ml-4 shadow-[0_4px_0_rgba(245,158,11,1)] flex items-center justify-center">
                    <div className="w-3 h-3 bg-amber-500 rounded-full"></div>
                 </div>

                 {/* Card */}
                 <div className="ml-16 md:ml-0 w-full md:w-[calc(50%-40px)] group perspective">
                    <div className="bg-white dark:bg-slate-900 border-x-4 border-t-2 border-b-[8px] border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 transition-all duration-500 hover:-translate-y-2 hover:shadow-[0_12px_0_rgba(226,232,240,1)] hover:border-amber-400">
                       <div className="flex justify-between items-start mb-6">
                          <span className="bg-amber-100 dark:bg-amber-500/20 text-amber-700 dark:text-amber-400 border-2 border-amber-200 dark:border-amber-700 px-4 py-2 rounded-[1rem] text-[12px] font-black uppercase tracking-widest shadow-sm">{phase.duration}</span>
                          <span className="text-4xl font-display font-black text-slate-200 dark:text-slate-800 drop-shadow-sm">0{idx + 1}</span>
                       </div>
                       
                       <h3 className="text-3xl font-display font-black text-slate-800 dark:text-slate-100 mb-4 group-hover:text-amber-600 transition-colors">{phase.title}</h3>
                       <p className="text-slate-500 dark:text-slate-400 text-lg font-bold leading-relaxed mb-8">{phase.description}</p>
                       
                       {/* Topics Dropdowns */}
                       <div className="space-y-4">
                          {phase.topics?.map((topic, topicIdx) => {
                             const topicId = `${idx}-${topicIdx}`;
                             const isExpanded = expandedTopic === topicId;
                             
                             return (
                                <div key={topicIdx} className="border-2 border-slate-200 dark:border-slate-800 rounded-[1.5rem] overflow-hidden bg-slate-50 dark:bg-slate-950/30 transition-all hover:border-amber-400 hover:shadow-[0_4px_0_rgba(251,191,36,1)]">
                                   <button 
                                     onClick={() => toggleTopic(topicId)}
                                     className="w-full flex items-center justify-between p-5 hover:bg-white dark:hover:bg-slate-900 shadow-sm transition-colors"
                                   >
                                      <div className="flex items-center gap-4">
                                         <div className={`p-2 rounded-[1rem] shadow-sm ${isExpanded ? 'bg-amber-500 text-white shadow-[0_4px_0_rgba(245,158,11,1)]' : 'bg-white border-2 border-slate-200 text-slate-500'}`}>
                                            <Atom size={20} className={isExpanded ? "animate-spin-slow" : ""} />
                                         </div>
                                         <span className="font-black text-base text-slate-700 dark:text-slate-200">{topic.title}</span>
                                      </div>
                                      {isExpanded ? <ChevronUp size={24} className="text-amber-500" strokeWidth={3} /> : <ChevronDown size={24} className="text-slate-400" strokeWidth={3} />}
                                   </button>
                                   
                                   {isExpanded && (
                                      <div className="p-4 pt-0 border-t border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 animate-in slide-in-from-top-2 duration-200">
                                         <div className="mb-4">
                                            <p className="text-[10px] uppercase font-black text-slate-400 tracking-wider mb-2 mt-4">Key Concepts</p>
                                            <div className="flex flex-wrap gap-2">
                                               {topic.concepts.map((concept, i) => (
                                                  <span key={i} className="text-[11px] font-black uppercase tracking-widest bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 px-3 py-1.5 rounded-lg border-2 border-slate-200 dark:border-slate-700 shadow-sm">
                                                     {concept}
                                                  </span>
                                               ))}
                                            </div>
                                         </div>

                                         <div className="space-y-2">
                                            <p className="text-[10px] uppercase font-black text-slate-400 tracking-wider mb-2">Recommended Resources</p>
                                            {topic.resources.map((res, i) => (
                                               <a key={i} href={res.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 p-3 rounded-xl hover:bg-amber-50 dark:hover:bg-amber-900/20 group/link transition-colors border-2 border-transparent hover:border-amber-200">
                                                  {getResourceIcon(res.type)}
                                                  <span className="text-xs font-bold text-slate-600 dark:text-slate-300 flex-1 truncate group-hover/link:text-amber-700 dark:group-hover/link:text-amber-400">{res.title}</span>
                                                  <ArrowRight size={12} className="opacity-0 group-hover/link:opacity-100 -translate-x-2 group-hover/link:translate-x-0 transition-all text-amber-600" strokeWidth={3} />
                                               </a>
                                            ))}
                                         </div>
                                      </div>
                                   )}
                                </div>
                             );
                          })}
                       </div>
                    </div>
                 </div>

                 {/* Spacer */}
                 <div className="hidden md:block md:w-[calc(50%-40px)]"></div>
              </div>
            ))}
         </div>
      </div>
    </div>
  );

  return (
    <div className="animate-reveal min-h-screen">
      {viewMode === 'input' ? (
        <div className="flex flex-col items-center justify-center py-20 px-4 max-w-4xl mx-auto text-center">
           <div className="w-28 h-28 bg-amber-400 border-4 border-amber-500 dark:border-amber-600 rounded-[2rem] flex items-center justify-center text-slate-900 mb-12 shadow-[0_8px_0_rgba(217,119,6,1)] rotate-3 hover:rotate-6 transition-transform">
              <Rocket size={56} strokeWidth={2.5} className="animate-pulse" />
           </div>
           <h1 className="text-5xl md:text-7xl lg:text-[5.5rem] font-display font-black text-slate-800 dark:text-white mb-6 tracking-tighter drop-shadow-sm leading-tight">
             Master <span className="text-amber-500">Anything.</span>
           </h1>
           <p className="text-xl md:text-2xl text-slate-500 dark:text-slate-400 mb-16 max-w-3xl font-bold leading-relaxed">
             From coding to cooking, startups to science. Our AI constructs a perfect path for any quest you desire.
           </p>
           
           <div className="w-full max-w-2xl relative group z-20">
              <div className="absolute -inset-1 bg-slate-200 dark:bg-slate-800 rounded-[2.5rem] blur-xl opacity-25 group-hover:opacity-50 transition duration-1000"></div>
              <div className="relative flex flex-col items-center bg-slate-50 dark:bg-slate-900 rounded-[2.5rem] shadow-[0_6px_0_rgba(226,232,240,1)] border-x-4 border-t-2 border-b-[8px] border-slate-200 dark:border-slate-800 p-2 hover:-translate-y-1 hover:shadow-[0_10px_0_rgba(226,232,240,1)] transition-all">
                 <div className="flex items-center w-full">
                   <Search className="ml-6 text-slate-400 group-focus-within:text-amber-500 transition-colors shrink-0" size={28} strokeWidth={3} />
                   <input 
                     type="text" 
                     value={input}
                     onChange={(e) => setInput(e.target.value)}
                     onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                     placeholder="e.g. Master React, AI Engineer..."
                     className="w-full bg-transparent border-none text-2xl font-black text-slate-800 dark:text-white placeholder:text-slate-300 focus:ring-0 px-6 py-6 outline-none"
                   />
                   <button 
                    onClick={handleGenerate}
                    disabled={loading || !input.trim()}
                    className="bg-amber-400 text-slate-900 p-6 rounded-[1.5rem] hover:translate-y-[2px] active:translate-y-[6px] active:shadow-none transition-all disabled:opacity-50 disabled:transform-none disabled:shadow-[0_4px_0_rgba(217,119,6,1)] shadow-[0_4px_0_rgba(217,119,6,1)] flex items-center justify-center border-2 border-amber-500 mr-2"
                   >
                     {loading ? <Loader2 className="animate-spin" size={28} strokeWidth={3} /> : <Rocket size={28} strokeWidth={3} />}
                   </button>
                 </div>
                 
                 {/* Generation Modifiers */}
                 <div className="w-full flex flex-col md:flex-row items-center gap-4 px-6 pb-4 pt-2 border-t-2 border-dashed border-slate-200 dark:border-slate-800">
                    <div className="flex flex-col text-left flex-1 w-full">
                       <label className="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-2 pl-1">Level</label>
                       <select 
                         value={experienceLevel} 
                         onChange={(e) => setExperienceLevel(e.target.value)}
                         className="w-full bg-white dark:bg-slate-950 border-2 border-slate-200 dark:border-slate-800 rounded-xl px-4 py-3 font-bold text-sm text-slate-600 dark:text-slate-300 outline-none focus:border-amber-400"
                       >
                          <option value="Beginner">Beginner (No prep)</option>
                          <option value="Intermediate">Intermediate (Some prep)</option>
                          <option value="Advanced">Advanced (Expert prep)</option>
                       </select>
                    </div>
                    <div className="flex flex-col text-left flex-1 w-full">
                       <label className="text-[10px] font-black uppercase text-slate-400 tracking-widest mb-2 pl-1">Pace</label>
                       <select 
                         value={timeCommitment} 
                         onChange={(e) => setTimeCommitment(e.target.value)}
                         className="w-full bg-white dark:bg-slate-950 border-2 border-slate-200 dark:border-slate-800 rounded-xl px-4 py-3 font-bold text-sm text-slate-600 dark:text-slate-300 outline-none focus:border-amber-400"
                       >
                          <option value="5 hours/week">Casual (~5h / week)</option>
                          <option value="15 hours/week">Balanced (~15h / week)</option>
                          <option value="30 hours/week">Intensive (~30h / week)</option>
                       </select>
                    </div>
                 </div>
              </div>
           </div>

           {error && (
             <div className="mt-8 flex items-center gap-3 text-red-600 bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-900/50 px-6 py-4 rounded-2xl text-sm font-bold animate-pulse">
               <AlertCircle size={20} />
               {error}
             </div>
           )}

           <div className="flex flex-wrap gap-4 mt-16 justify-center">
              {['Launch a Startup', 'Learn Piano', 'Data Science', 'Speak Japanese'].map(tag => (
                <button 
                  key={tag}
                  onClick={() => { setInput(tag); }}
                  className="px-6 py-4 bg-white dark:bg-slate-900 border-2 border-slate-200 dark:border-slate-800 rounded-[1.5rem] text-[12px] font-black text-slate-500 uppercase tracking-[0.2em] shadow-[0_4px_0_rgba(226,232,240,1)] hover:translate-y-[2px] hover:border-amber-400 hover:text-amber-600 hover:shadow-[0_2px_0_rgba(251,191,36,1)] active:translate-y-[4px] active:shadow-none transition-all"
                >
                  {tag}
                </button>
              ))}
           </div>

           {history.length > 0 && (
             <div className="mt-24 w-full text-left animate-in slide-in-from-bottom-5 duration-500">
                <div className="flex items-center gap-4 mb-8">
                   <h3 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] relative flex items-center gap-2">
                     <Layers size={14} /> Created Roadmaps
                   </h3>
                   <div className="h-px flex-1 bg-slate-200 dark:bg-slate-800"></div>
                </div>
                
                <div className="grid md:grid-cols-2 gap-6">
                  {history.map(item => (
                    <div 
                      key={item.id} 
                      onClick={() => { setResult(item.road_data); setCurrentRoadmapId(item.id); setLastQuery(item.role || ''); setViewMode('roadmap'); }}
                      className="group bg-white dark:bg-slate-900 border-x-4 border-t-2 border-b-[8px] border-slate-200 dark:border-slate-800 p-6 rounded-[2rem] cursor-pointer hover:border-amber-400 dark:hover:border-amber-500 hover:-translate-y-2 hover:shadow-[0_10px_0_rgba(226,232,240,1)] dark:hover:shadow-[0_10px_0_rgba(30,41,59,1)] transition-all flex justify-between items-start"
                    >
                       <div>
                          <div className="flex items-center gap-2 mb-3">
                             <span className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]"></span>
                             <span className="text-[10px] uppercase font-black text-slate-400 tracking-widest">{new Date(item.created_at).toLocaleDateString()}</span>
                          </div>
                          <h4 className="font-black text-slate-800 dark:text-slate-200 text-xl group-hover:text-amber-600 dark:group-hover:text-amber-400 transition-colors mb-1">{item.role}</h4>
                          <p className="text-sm font-bold text-slate-500 line-clamp-1">{item.title}</p>
                       </div>
                       <button 
                         onClick={(e) => handleDelete(e, item.id)}
                         className="p-3 text-slate-300 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-all opacity-0 group-hover:opacity-100 hover:scale-110 active:scale-95"
                       >
                          <Trash2 size={20} strokeWidth={2.5} />
                       </button>
                    </div>
                  ))}
                </div>
             </div>
           )}
        </div>
      ) : viewMode === 'course' && generatedCourse ? (
        <CourseView initialCourseData={generatedCourse} onBack={() => { setResult(null); setViewMode('input'); }} />
      ) : (
        result && <RoadmapView roadmap={result} />
      )}

      {/* Share Modal — lives at top level so state updates work */}
      {shareModal && (
        <div className="fixed inset-0 z-[300] flex items-start justify-center pt-20 px-4 pointer-events-none">
          <div className="pointer-events-auto bg-white/95 dark:bg-slate-900/95 backdrop-blur-xl w-full max-w-lg rounded-[2rem] border border-slate-200/80 dark:border-slate-700/80 shadow-[0_32px_64px_-12px_rgba(0,0,0,0.25)] dark:shadow-[0_32px_64px_-12px_rgba(0,0,0,0.6)] animate-in slide-in-from-top-4 zoom-in-95 duration-300 overflow-hidden">
            <div className="h-1 w-full bg-gradient-to-r from-blue-400 via-indigo-400 to-violet-400" />
            <div className="p-7">
              <div className="flex items-start justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-blue-100 dark:bg-blue-500/20 flex items-center justify-center">
                    <Share2 size={18} className="text-blue-500" />
                  </div>
                  <div>
                    <p className="text-[10px] font-black text-blue-500 uppercase tracking-[0.2em]">Public Link</p>
                    <h3 className="text-lg font-display font-black text-slate-800 dark:text-white">Share Roadmap</h3>
                  </div>
                </div>
                <button
                  onClick={() => setShareModal(false)}
                  className="w-8 h-8 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-slate-400 hover:text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10 hover:rotate-90 transition-all duration-200"
                >
                  <X size={14} strokeWidth={2.5} />
                </button>
              </div>
              <p className="text-sm text-slate-500 dark:text-slate-400 font-medium mb-5">
                Anyone with this link can view the full roadmap — no login required.
              </p>
              {getShareUrl() ? (
                <>
                  <div className="flex gap-2 mb-4">
                    <div className="flex-1 bg-slate-50 dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 rounded-xl px-4 py-3 text-sm font-mono text-slate-600 dark:text-slate-300 truncate select-all">
                      {getShareUrl()}
                    </div>
                    <button
                      onClick={handleCopyLink}
                      className={`px-5 py-3 rounded-xl font-black uppercase tracking-widest text-[11px] transition-all shrink-0 flex items-center gap-2
                        ${copied
                          ? 'bg-emerald-500 text-white'
                          : 'bg-blue-600 text-white hover:translate-y-[2px] active:translate-y-[4px]'
                        }`}
                    >
                      {copied ? <><CheckCircle2 size={14} /> Copied!</> : 'Copy'}
                    </button>
                  </div>
                  <a
                    href={getShareUrl() || '#'}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-full py-3.5 rounded-xl font-black uppercase tracking-widest text-[11px] bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-700 transition-all flex items-center justify-center gap-2"
                  >
                    <ArrowRight size={14} strokeWidth={3} /> Open in New Tab
                  </a>
                </>
              ) : (
                <div className="space-y-3">
                  <div className="bg-amber-50 dark:bg-amber-500/10 border-2 border-amber-200 dark:border-amber-500/30 rounded-xl p-4 text-sm font-bold text-amber-700 dark:text-amber-400">
                    Link is being generated... If this persists, your Supabase RLS policy may be blocking saves. Run the fix SQL in your Supabase dashboard.
                  </div>
                  <button
                    onClick={async () => {
                      if (result && userId !== 'mock-user-id') {
                        const saved = await saveRoadmap(result, userId);
                        if (saved) setCurrentRoadmapId(saved.id);
                      }
                    }}
                    className="w-full py-3 rounded-xl font-black uppercase tracking-widest text-[11px] bg-blue-600 text-white hover:bg-blue-700 transition-all flex items-center justify-center gap-2"
                  >
                    Retry Save
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};


export default RoadmapGenerator;
